# Version: 1
# Application for Common Resources (Namespace, Ingress, TLS)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podverse-alpha-common
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/suorcd/podverse-ops.git
    targetRevision: feature/k3s01
    path: k8s/alpha/common
  destination:
    server: https://kubernetes.default.svc
    namespace: podverse-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
