apiVersion: v1
data:
    DB_READ_PASSWORD: ENC[AES256_GCM,data:omTwUslnelebgZFOKgV5oyix+oPf+Vyi1OIChc8Qkvg=,iv:JiE0zmHLdI8NXIa7MYS4UXf/EfCqJod1DFTEi0vQjDw=,tag:36S2rLqVrAIDdETamkLu5w==,type:str]
    DB_READ_WRITE_PASSWORD: ENC[AES256_GCM,data:2ph64ki6usNPGOwTRxVfdlmdI9EaukOEEYRN1tCY1AY=,iv:J3ASMozqMULJos9JxGLv/5D3B+gsC3QPMU7C/Q4SJyI=,tag:Ofgwv6rxEQaRxp7eZXj/oA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:eP3xK1GR+CldMKVl,iv:v4YxRYXE2mBy1PfOcdDRU2WJImt0uloyZeBVmvRfoUU=,tag:4y4V1Cv7/UznN62OlOSiKQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/L9RGg/hGqFhrYk5t0s/HddG6AFJyrRj9con7V0D/Qg=,iv:Mfg7hY2amgjqFhmG/S4oSLtDjBVDbAKHSsnNvrAe59Q=,tag:oexz0qVkpiDj+hiUFKEcWg==,type:str]
    POSTGRES_READ_PASSWORD: ENC[AES256_GCM,data:lcABBPAHtyMAvSn4sbU+IzJHXTDFB8R6Nf6OckuZulg=,iv:dHgf0WWUMOu5tX0T5P1pqTrfmnKrZqz+HQ4m5nDQlUA=,tag:64yDnl3WZjWJpB+XTPlEmg==,type:str]
    POSTGRES_READ_WRITE_PASSWORD: ENC[AES256_GCM,data:GsSQHORE/B2NtCfGOr3JH8y942pHXdwRZxg+cnCliT4=,iv:AUp8qBT2FHybWBeAck3FTMUSp5tdrUGFrZoeT2VBLAk=,tag:ePUxFh3Rzp9fKjTDjfZMCQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:t1sOwL24exh/ds+d,iv:JSgkuRGvLIdTTS2VmM/R8SFX8jfuAt+oAeSPSY0xwgw=,tag:MzKKeZc+0UjZj9AW/vYPQQ==,type:str]
kind: Secret
metadata:
    name: podverse-db-secret
    namespace: podverse-alpha
sops:
    age:
        - recipient: age1su7dpcrqydl85x7xpvjzuvquwh0fjk7afjfenw7cerf8ttuhlvls8mcyja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmpRbVRSL2FHd3RoNXc3
            a2ptVjhib1dUNk1uNG5SMWF6MUxKMklwTml3CmdyQ0tlYk5PbjByVSs3WUtUdEVD
            WEd0QUpwbi9GVkNKangzTW9RL25yUVEKLS0tIGtVZmptY1lrbFAwZGl0V2djY3JD
            REpsNEFCTkdHY2UxeDVxdTJJNUNZWW8KLmaAcAgfwphhgkrpuPICKpGl3QPZHkAv
            Jkw3/QFNj9F6rOj+gQ8lazejidqNmrakPw/rXbr6vBydkhX+Ck9cYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T03:11:08Z"
    mac: ENC[AES256_GCM,data:SxD0gBUE4hmNeulBONZKn3GO5XC4axs2S3q4cnx6hxo0zXmw1xBeh5gxT0L6OvN3tibi+Yj3V33PslrRb/jBpyN5svn6CLOzPzjcJcKLfXksRCtXCtrwHOsTTKnL7unikBMPV+2c5IC5Ts0XU5BUbsbYtPbRqLsRfsyjFEvw+N0=,iv:FZzB+K7nFP6sAOP6GPrIsI2ipGyRYZ3ivnSFz6RKCvk=,tag:lK5sk1vuUUdckevQmyRz0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
