# Version: 1
# This kustomization file bundles common infrastructure components.
# It includes the namespace, ingress rules, and TLS security policies.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./00-namespace.yaml
  - ../../base/common/01-ingress.yaml
  - ../../base/common/02-tls-options.yaml

labels:
  - pairs:
      app: podverse-common
      environment: alpha
    # This ensures the labels are also applied to the selectors, 
    # so the Service correctly finds the Pods.
    includeSelectors: true