# Version: 2
# Pattern: Suspended CronJob (Manual Trigger Only)
# This defines the "task" but ensures it NEVER runs automatically.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ops-db-verify-account
  namespace: podverse-alpha
spec:
  # Standard "don't run" config:
  schedule: "* * * * *"  # Dummy schedule (required but ignored)
  suspend: true          # <--- PREVENTS AUTOMATIC EXECUTION
  concurrencyPolicy: Forbid
  
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
          - name: psql
            image: postgres:18.1
            command: 
              - "psql"
              - "-h"
              - "podverse-db"
              - "-U"
              - "postgres"
              - "-d"
              - "postgres"
              - "-c"
              - "UPDATE account SET verified = true where id = 1;"
            envFrom:
            - secretRef:
                name: podverse-db-opaque
          restartPolicy: Never