apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-parser-live
  namespace: podverse-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-parser-live
  template:
    metadata:
      labels:
        app: worker-parser-live
    spec:
      containers:
      - name: worker
        image: ghcr.io/podverse/podverse-workers/podverse-workers:5.1.10-alpha.0
        command: ["npm", "run", "mq_rss_run_parser", "--", "-q", "rss-live"]
        envFrom:
        - configMapRef:
            name: podverse-workers-config
        - secretRef:
            name: podverse-workers-opaque
      #   volumeMounts:
      #   - name: firebase-config
      #     mountPath: /opt/config/firebase-key.json
      #     subPath: firebase-key.json
      #     readOnly: true
      # volumes:
      # - name: firebase-config
      #   secret:
      #     secretName: podverse-workers-firebase-opaque
