# The secrets will be base64 encoded in the real file.
apiVersion: v1
data:
    ARTEMIS_PASSWORD: "CHANGE_ME"
    ARTEMIS_USER: "admin"
    MESSAGE_QUEUE_PASSWORD: "CHANGE_ME"
    MESSAGE_QUEUE_USERNAME: "admin"
kind: Secret
metadata:
    name: podverse-alpha-mq-opaque
    namespace: podverse-alpha