# The secrets will be base64 encoded in the real file.
apiVersion: v1
data:
    PODCAST_INDEX_AUTH_KEY: "CHANGE_ME"
    PODCAST_INDEX_SECRET_KEY: "CHANGE_ME"
kind: Secret
metadata:
    name: podverse-workers-opaque
    namespace: podverse-alpha