# The secrets will be base64 encoded in the real file.
apiVersion: v1
data:
    AUTH_JWT_SECRET: "CHANGE_ME_TO_RANDOM_STRING"
    MAILER_PASSWORD: ""
kind: Secret
metadata:
    name: podverse-alpha-api-opaque
    namespace: podverse-alpha