# The secrets will be base64 encoded in the real file.
apiVersion: v1
data:
    DB_READ_PASSWORD: "CHANGE_ME"
    DB_READ_WRITE_PASSWORD: "CHANGE_ME"
    POSTGRES_DB: "postgres"
    POSTGRES_PASSWORD: "CHANGE_ME"
    POSTGRES_READ_PASSWORD: "CHANGE_ME"
    POSTGRES_READ_WRITE_PASSWORD: "CHANGE_ME"
    POSTGRES_USER: "postgres"
kind: Secret
metadata:
    name: podverse-alpha-db-opaque
    namespace: podverse-alpha